### ISSUE TITLE
Crash in updater.py

### ISSUE THREAD

**Issue by zachkont** [zachkont/dotaUpdatesBot#35]
```
Traceback (most recent call last):
  File "./updater.py", line 148, in <module>
    check_for_updates_and_notify()
  File "./updater.py", line 143, in check_for_updates_and_notify
    posts = get_dota2blog_posts()
  File "./updater.py", line 34, in get_dota2blog_posts
    return get_rss_posts("http://blog.dota2.com/feed/", "Dota 2 blog feed not accessible.")
  File "./updater.py", line 24, in get_rss_posts
    if feed and feed.status:
  File "/home/user/.local/lib/python2.7/site-packages/feedparser.py", line 400, in __getattr__
    raise AttributeError, "object has no attribute '%s'" % key
AttributeError: object has no attribute 'status'
Exception in thread WorkerThread1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/home/user/.local/lib/python2.7/site-packages/telebot/util.py", line 56, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
```

**Comment by TimJentzsch** [comment]
Does this occure every 10 seconds / in every update cycle or did it only happen once?

**Comment by zachkont** [comment]
Happened once, tried a simple fix and it seems to be working fine so far, but the fix is only related to the updater

**Comment by TimJentzsch** [comment]
Ah, OK. Is #34 live already and if yes, did it cause any issues yet?

**Comment by zachkont** [comment]
This looks like it's been fixed.
