### ISSUE TITLE
Crash in main.py

### ISSUE THREAD

**Issue by zachkont** [zachkont/dotaUpdatesBot#38]
Error Log

```
Traceback (most recent call last):
  File "./main.py", line 191, in <module>
    bot.polling(none_stop=True, interval=0)
  File "/home/user/.local/lib/python2.7/site-packages/telebot/__init__.py", line 174, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/home/user/.local/lib/python2.7/site-packages/telebot/__init__.py", line 197, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/home/user/.local/lib/python2.7/site-packages/telebot/util.py", line 72, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/home/user/.local/lib/python2.7/site-packages/telebot/util.py", line 53, in run
    task(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/telebot/__init__.py", line 120, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/user/.local/lib/python2.7/site-packages/telebot/__init__.py", line 90, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout)
  File "/home/user/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 131, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/user/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 26, in _make_request
    result = requests.request(method, request_url, params=params, files=files)
  File "/home/user/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
Exception in thread WorkerThread2 (most likely raised during interpreter shutdown):Exception in thread WorkerThread1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/home/user/.local/lib/python2.7/site-packages/telebot/util.py", line 56, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'

```

**Comment by TimJentzsch** [comment]
Seems to have the same origin as #35

**Comment by zachkont** [comment]
New error log:
```
Traceback (most recent call last):
  File "./main.py", line 191, in <module>
    hero['localized_name'] + " " +
  File "/home/user/.local/lib/python2.7/site-packages/telebot/__init__.py", line 174, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/home/user/.local/lib/python2.7/site-packages/telebot/__init__.py", line 197, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/home/user/.local/lib/python2.7/site-packages/telebot/util.py", line 72, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/home/user/.local/lib/python2.7/site-packages/telebot/util.py", line 53, in run
    task(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/telebot/__init__.py", line 120, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/user/.local/lib/python2.7/site-packages/telebot/__init__.py", line 90, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout)
  File "/home/user/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 131, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/user/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 26, in _make_request
    result = requests.request(method, request_url, params=params, files=files)
  File "/home/user/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
Exception in thread WorkerThread1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/home/user/.local/lib/python2.7/site-packages/telebot/util.py", line 56, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
Exception in thread WorkerThread2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/home/user/.local/lib/python2.7/site-packages/telebot/util.py", line 56, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
```
